---

- name: Nomad Init Script
  template:
    src: "etc/init.d/nomad.{{ansible_os_family}}.j2"
    dest: /etc/init.d/nomad
    owner: root
    group: root
    mode: "0755"

- name: Enable Nomad at boot
  service:
    name: nomad
    enabled: yes
    state: "{{ (nomad_started) | ternary('started', 'stopped') }}"
  when: nomad_start_at_boot

# vi:ts=2:sw=2:et:ft=yaml
