---

- name: Nomad group
  group:
    state: present
    name: "{{nomad_group}}"
    system: yes

- name: Nomad user
  user:
    state: present
    name: "{{nomad_user}}"
    group: "{{nomad_group}}"
    comment: "Nomad Service"
    shell: "/bin/nologin"
    system: yes

# vi:ts=2:sw=2:et:ft=yaml
