---

- name: Nomad group
  group:
    state: present
    name: "{{nomad_group}}"
    system: yes

- name: Nomad user
  user:
    state: present
    name: "{{nomad_user}}"
    group: "{{nomad_group}}"
    comment: "Nomad Service"
    shell: "/bin/nologin"
    system: yes

- block:

  - name: Docker group verification
    getent:
      database: group
      key: "{{nomad_docker_group}}"

  - name: Add Nomad user to Docker group
    user:
      name: "{{nomad_user}}"
      groups: "{{nomad_docker_group}}"
      append: yes

  when: nomad_user_to_docker

# vi:ts=2:sw=2:et:ft=yaml
