---

- name: nomad start
  service:
    name: nomad
    state: started
  when: nomad_started

- name: nomad stop
  service:
    name: nomad
    state: stopped

- name: nomad restart
  service:
    name: nomad
    state: restarted
  when: nomad_started

# vi:ts=2:sw=2:et:ft=yaml
